const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `There's nothing like plain buttermilk pancakes topped with maple syrup. But, if you're in the mood to add something extra to your breakfast, you can! Optional mix-ins include chocolate chips, berries, and nuts. You could also add cinnamon and vanilla to the batter for a little extra warmth. Instead of syrup, you could top your buttermilk pancakes with jam or honey for a sweet twist on a classic.`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Diner Double Cheeseburger features two hand-pressed beef patties, topped with melted American cheese, caramelized onions, and All-American sauce, all sandwiched between two brioche buns.`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `“Godzilla” is topped with whipped cream and/or vanilla ice cream. These heaps of chocolate malt powder are added to give extra crunch to the drinks.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Onions, Sweet Bell Peppers & Fresh Mushrooms, Topped with Shredded Marble Cheese & 2 Eggs Served Your Way. Served with a Side of Smoked Bacon, Ham OR Link Sausage.`,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `You'll love this easy but tasty egg salad recipe that works as a starter or light lunch.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Love the combination of Oreo cookies and ice cream? Then a delicious and decadent Oreo milkshake is for you! This sweet treat is perfect for celebrations, special occasions, or simply to cool you down on a hot summer day.`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `This high protein breakfast log has all the best parts of breakfast. Warm and fluffy eggs, crispy hash browns, cheesiness, and the unmistakable savoriness of bacon.`,
  },
  {
    id: 8,
    title: "American classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `From grilled cheese and burgers to cheesecake and apple pie, these classic American recipes are irresistible. `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Pack in the protein with one of our delicious protein shake recipes for you and your quarantine buddy! `,
  },
];
export default menu;
